import a_1 from "./a-1.jpg";
import a_2 from "./a-2.jpg";
import a_3 from "./a-3.jpg";
import a_4 from "./a-4.jpg";
import a_5 from "./a-5.jpg";
import a_6 from "./a-6.jpg";
import a_7 from "./a-7.jpg";
import a_8 from "./a-8.jpg";
import b_1 from "./b-1.jpg";
import b_2 from "./b-2.jpg";
import b_3 from "./b-3.jpg";
import b_4 from "./b-4.jpg";
import b_5 from "./b-5.jpg";
import b_6 from "./b-6.jpg";
import b_7 from "./b-7.jpg";
import b_8 from "./b-8.jpg";
import b_sun from "./b-sun.png";
import c_1 from "./c-1.jpg";
import c_2 from "./c-2.jpg";
import c_3 from "./c-3.jpg";
import c_4 from "./c-4.jpg";
import c_5 from "./c-5.jpg";
import c_6 from "./c-6.jpg";
import c_7 from "./c-7.jpg";
import c_8 from "./c-8.jpg";
import a_lion from "./a-lion.jpg";
import c_palm from "./c-palm.jpg";

export const A_IMAGES = [a_1, a_2, a_3, a_4, a_5, a_6, a_7, a_8];
export const B_IMAGES = [b_1, b_2, b_3, b_4, b_5, b_6, b_7, b_8];
export const C_IMAGES = [c_1, c_2, c_3, c_4, c_5, c_6, c_7, c_8];
export { a_lion, b_sun, c_palm };
