"""
Generate supabase/migrations/0007_catalog_seed.sql from src/lib/catalog-data.json
(itself generated by tools/parse_stock.py from the client's stock sheet).

There is no price or SKU data yet, so every variant seeds with price = 0 and
is_visible = false. Nothing on the site can be bought until an admin sets a
real price and switches it on. Units-per-box is kept as a note in the
description for now (no dedicated column for it yet).

Re-run whenever catalog-data.json changes:
    python tools/gen_catalog_seed.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "lib" / "catalog-data.json"
OUTPUT = ROOT / "supabase" / "migrations" / "0007_catalog_seed.sql"


def split_variant_name(name: str):
    """Mirror src/lib/variants.ts splitVariantName: pull the base name and
    the first option's label out of a name like 'Ring Joint Holder - Silver'
    or 'Raw Drawstring Bag (Beige)'."""
    m = re.match(r"^(.*?)\s*[-–]\s*([^-–]+)$", name)
    if not m:
        m = re.match(r"^(.*?)\s*\(([^)]+)\)$", name)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    return name, "Default"


def esc(s: str) -> str:
    return s.replace("'", "''")


def main():
    categories = json.loads(SOURCE.read_text(encoding="utf-8"))

    lines = [
        "-- Generated by tools/gen_catalog_seed.py from src/lib/catalog-data.json.",
        "-- Do not hand-edit: re-run the script instead.",
        "--",
        "-- Seeds the 19 categories and 408 products from the client's stock sheet.",
        "-- No price/SKU data exists yet, so every variant is price = 0 and hidden",
        "-- (is_visible = false). An admin must set a real price before a product",
        "-- can show or sell.",
        "",
        "insert into public.categories (slug, name, sort_order) values",
    ]

    cat_rows = [f"  ('{esc(c['slug'])}', '{esc(c['name'])}', {i})" for i, c in enumerate(categories)]
    lines.append(",\n".join(cat_rows) + "\non conflict (slug) do nothing;")
    lines.append("")

    product_rows = []
    variant_rows = []
    total_products = 0
    total_variants = 0

    for c in categories:
        for p_index, p in enumerate(c["products"]):
            total_products += 1
            if p["variants"]:
                base, first_label = split_variant_name(p["name"])
                variant_specs = [first_label] + [v["label"] for v in p["variants"]]
            else:
                base = p["name"]
                variant_specs = ["Default"]

            note = f"{int(p['unitsPerBox'])} per box" if p["unitsPerBox"] else ""
            product_rows.append(
                "  ((select id from public.categories where slug = '{}'), "
                "'{}', '{}', '{}', false, {})".format(
                    esc(c["slug"]), esc(p["slug"]), esc(base), esc(note), p_index
                )
            )

            for v_index, label in enumerate(variant_specs):
                total_variants += 1
                variant_rows.append(
                    "  ((select id from public.products where slug = '{}'), '{}', 0, 0, false, {})".format(
                        esc(p["slug"]), esc(label), v_index
                    )
                )

    lines.append("insert into public.products (category_id, slug, name, description, is_visible, sort_order) values")
    lines.append(",\n".join(product_rows) + "\non conflict (slug) do nothing;")
    lines.append("")

    lines.append("insert into public.product_variants (product_id, label, price, stock_qty, is_visible, sort_order) values")
    lines.append(",\n".join(variant_rows) + ";")
    lines.append("")

    lines.append("-- Verify:")
    lines.append(f"--   select count(*) from public.categories;        -- {len(categories)}")
    lines.append(f"--   select count(*) from public.products;          -- {total_products}")
    lines.append(f"--   select count(*) from public.product_variants;  -- {total_variants}")
    lines.append("--   select count(*) from public.products where is_visible;         -- 0 (nothing shows until priced)")
    lines.append("--   select slug, name from public.products where name ~ '- | \\(' limit 5;  -- base names only, no ' - Silver' suffix")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(categories)} categories, {total_products} products, {total_variants} variants)")


if __name__ == "__main__":
    main()
